### ISSUE TITLE
[SUGGESTION] Allow for trinkets to give warmth or make a player colder, depending on tags

### ISSUE THREAD

**Issue by Sunconure11** [Globox1997/EnvironmentZ#101]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Some mods add stuff like scarves, capes, etc, but these would work best if they had some impact on your body temperature. Perhaps this could be added, if possible?

**Comment by Globox1997** [comment]
Compat can be added by those mods.
