### ISSUE TITLE
Crashes on Anvil Screen when item NBT is null

### ISSUE THREAD

**Issue by Szymzal** [Globox1997/EnvironmentZ#105]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

2.0.5

### Describe the Issue

I am using Create mod with Create: Steam 'n' Rails mod addon.
When trying to change name in anvil of conductor's cape (Create: Steam 'n' Rails mod item), it crashes.

Probably the cause is in:
https://github.com/Globox1997/EnvironmentZ/blob/6982d456b1f2e6d504468108f43cdbc6c359745c/src/main/java/net/environmentz/mixin/AnvilScreenHandlerMixin.java#L74

When NBT is null which is the case in conductor's cape, the client crashes

### latest.log

[latest.log](https://github.com/Globox1997/EnvironmentZ/files/12648646/latest.log)

### Do you use any other mods except the required ones?

Create Fabric, Create: Steam 'n' Rails, StackDeobfuscator

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/EnvironmentZ/commit/14e32e4db1381881412256cbce7d2b337e6be922](https://github.com/Globox1997/EnvironmentZ/commit/14e32e4db1381881412256cbce7d2b337e6be922)
Thanks for report.
