### ISSUE TITLE
Cannot apply polar bear fur to armor in 1.20.1

### ISSUE THREAD

**Issue by Twobis** [Globox1997/EnvironmentZ#107]
### Minecraft Version

1.20.x

### Mod Loader Version

47.1.3

### Mod Version

2.0.5

### Describe the Issue

You cannot combine polar bear fur with armor in 1.20.1 as the smithing table gui has changed.

### latest.log

.

### Do you use any other mods except the required ones?

.

**Comment by himansure** [comment]
same

**Comment by Globox1997** [comment]
In later versions you have to add polar bear fur at the anvil.

**Comment by himansure** [comment]
> In later versions you have to add polar bear fur at the anvil.

when?

**Comment by Globox1997** [comment]
1.20+

**Comment by himansure** [comment]
> 1.20+

update fabric loader in 0.14.22, i cannot update in 0.14.24
