### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by lanwoodall423** [Globox1997/EnvironmentZ#109]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.24

### Mod Version

2.0.6

### Describe the Issue

Crash on launch. Does not occur when EnvironmentZ is removed. Only occurs with latest version. 2.0.5 works.

### latest.log

[latest.log](https://github.com/Globox1997/EnvironmentZ/files/13326796/latest.log)

**Comment by bons66** [comment]
Same problem. MC 1.20.1 / Fabric 0.14.24 / Mod 2.0.6 (2.0.5 - work fine)
[latest.log](https://github.com/Globox1997/EnvironmentZ/files/13328631/latest.log)

**Comment by xR4YM0ND** [comment]
Campfire Feature Crash

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/4b9556cd8e23cac775d3b37e0d5e5a6623b74ddc](https://github.com/Globox1997/EnvironmentZ/commit/4b9556cd8e23cac775d3b37e0d5e5a6623b74ddc)
