### ISSUE TITLE
What about hot biomes like desert?

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/EnvironmentZ#11]
This mod only covers freezing in cold biomes. Why not add overheat damage?

**Comment by RDKRACZ** [comment]
And then the Potion of Fire Resistance could make the player invulnerable to the heat damage.

**Comment by Gappysona** [comment]
Heat is in the Dehydration mod, and will be removed and placed into the EnvironmentZ mod in the near future

**Comment by Globox1997** [comment]
Added overheating [https://github.com/Globox1997/EnvironmentZ/commit/8c58429877e95524c6c12cc002228ae250ce4146](https://github.com/Globox1997/EnvironmentZ/commit/8c58429877e95524c6c12cc002228ae250ce4146)
