### ISSUE TITLE
[suggestion] compatibility and change

### ISSUE THREAD

**Issue by Disxconected** [Globox1997/EnvironmentZ#14]
as a compatibility/interaction with Primal Winter make EnvironmentZ treat all biomes as cold

also I propose  a change to the texture of the item/armor of insolated armors
here are some sample mock ups of an insolated diamond helmet 
![insolated_diamond_helmet_item](https://user-images.githubusercontent.com/10158133/115071859-ca50be80-9ec4-11eb-8c08-893b7dff11d6.png)
![insolated_diamond_helmet_armor](https://user-images.githubusercontent.com/10158133/115071874-cf157280-9ec4-11eb-95fe-4b9343faf203.png)

**Comment by Globox1997** [comment]
With the newest version, you can change the affected biome temperature, which will allow you to make all biomes get treated as cold :) Thanks for the texture but for now I will keep it simple with the insulated tooltip
