### ISSUE TITLE
Cold screen effect is applied in the Spectator mode.

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/EnvironmentZ#15]
Should be only in the Survival and Adventure mode.

Spectator
![image](https://user-images.githubusercontent.com/43277609/116760736-0bdd7f80-aa16-11eb-8177-57e94b1785cc.png)

Creative
![image](https://user-images.githubusercontent.com/43277609/116760755-15ff7e00-aa16-11eb-9f34-4d40a0a04c48.png)

**Comment by Globox1997** [comment]
Fixed with the latest version, thanks for info :)
