### ISSUE TITLE
Overheating doesnt Work Properly with Armors

### ISSUE THREAD

**Issue by CCCClear** [Globox1997/EnvironmentZ#17]
It's me, a big fan of your mods. 
I recently tested the latest version of the EnvironmentZ mod and found the following: 
While overheating occurs when the player is not wearing gear in a hot biome, cooling occurs when the player is wearing full armor.
I know, however, that in previous Dehydrating mod, heat was generated when the player wore even one piece of equipment in a hot biome, and the player didn't get hot without wearing any equipment. Although it's a different mod, I think your design philosophy is similar.
Is there something wrong with this, and maybe you can fix the irrationality in the next update?

**Comment by Globox1997** [comment]
yea thanks for the info, there was something wrong but I fixed it [https://github.com/Globox1997/EnvironmentZ/commit/12d3698f3cfc80d38ee75d72266118a070ffbc56](https://github.com/Globox1997/EnvironmentZ/commit/12d3698f3cfc80d38ee75d72266118a070ffbc56)
