### ISSUE TITLE
Cold effect causes first person view to go completely black

### ISSUE THREAD

**Issue by Corvyceps** [Globox1997/EnvironmentZ#18]
I'm using the newest 1.17 download along with a few other mods, including optifabric. The screen blackout only happens in survival when the little icon indicating cold pops up, like when entering certain biomes.

**Comment by xiaohangDAD** [comment]
I also encountered the same situation.
![image](https://user-images.githubusercontent.com/41426821/121799769-87129200-cc60-11eb-8618-685c9571f2e3.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/EnvironmentZ/commit/7bfd9605f2eb42e81e9ea73b3a8c21934d49ec9a](https://github.com/Globox1997/EnvironmentZ/commit/7bfd9605f2eb42e81e9ea73b3a8c21934d49ec9a)
thanks for reporting
