### ISSUE TITLE
Allow configuring which blocks can warm players up by default.

### ISSUE THREAD

**Issue by Sirmentio** [Globox1997/EnvironmentZ#2]
I think that through the configuration json, players and modpack authors should be able to adjust a list of blocks that could automatically get the "warm up" tag assigned to them. This could let more flexible balance changes occur across the entire modpack if a creator/player wishes.

**Comment by Globox1997** [comment]
I have a tag system for the warming up blocks so creator and players can just make a simple datapack if they want new blocks added to that list :)
