### ISSUE TITLE
Loosing enchantments in smiting table when insulate your armour

### ISSUE THREAD

**Issue by Nachtalb** [Globox1997/EnvironmentZ#20]
It seems that when you want to insulate your armour using the smithing table it will lose all enchantments (and other nbt data, like the display name etc.). 

It doesn't seem to be a Minecraft smithing table limitation, as you can change enchanted diamond tools/armour to netherite without loosing the enchantments etc. 

![image](https://user-images.githubusercontent.com/9467802/122594690-a564fd00-d067-11eb-9d86-e6505699715a.png)
![image](https://user-images.githubusercontent.com/9467802/122594683-a26a0c80-d067-11eb-8a8f-f5086ba6fe22.png)

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/462e234258d32cb6615c4b700a22181350505dbc](https://github.com/Globox1997/EnvironmentZ/commit/462e234258d32cb6615c4b700a22181350505dbc)
