### ISSUE TITLE
[bug w/ workaround] crash with dehydration / not compatible to dehydration anymore

### ISSUE THREAD

**Issue by TobiPeterG** [Globox1997/EnvironmentZ#28]
dehydration changed it's api in its latest version, so environmentz cant access the old one anymore, leading to game crashes.

A workaround is to use an older version of dehydration for now until the issue is fixed

**Comment by Globox1997** [comment]
Thanks for noticing me, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/ea7d5db3ddeeed027c73c4eb07bdd56dfe9365b7](https://github.com/Globox1997/EnvironmentZ/commit/ea7d5db3ddeeed027c73c4eb07bdd56dfe9365b7)
