### ISSUE TITLE
Overheating makes thirst enhancement

### ISSUE THREAD

**Issue by Muffintiem** [Globox1997/EnvironmentZ#29]
Players have no negative consequences from wearing armor while in a hot environment but hot environments cause dehydration after time. Preferably dehydration only occurs in hot environments. Jumping in water could lower the overheating which would not cause more dehydration to occur but wouldn't lower any existing dehydration.

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/EnvironmentZ/commit/699a9331032ea83e677495ace1028696fb8274e5](https://github.com/Globox1997/EnvironmentZ/commit/699a9331032ea83e677495ace1028696fb8274e5)
