### ISSUE TITLE
Can you add the ability in the configs to make it so overheating does damage to player like freezing does instead of dehydrating the player?

### ISSUE THREAD

**Issue by LBM09I5** [Globox1997/EnvironmentZ#31]

**Comment by Globox1997** [comment]
In the coming update overheating will reduce hunger (or thirst if dehydration mod is loaded) until it is gone which will then damage the player

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/EnvironmentZ/commit/61a6f91f019cc12e49740e184f6f7acf1c775ee4](https://github.com/Globox1997/EnvironmentZ/commit/61a6f91f019cc12e49740e184f6f7acf1c775ee4)
It doesn't do damage, instead it drains hunger
