### ISSUE TITLE
Overheating inbalance

### ISSUE THREAD

**Issue by Sir-Keeper** [Globox1997/EnvironmentZ#35]
Hello!
I've been enjoying your mod and noticed that the features might be unbalanced. That is, the mechanics for cold and heat.
There are a bit more ways to adapt to cold environments, than to warm ones. Surviving in the desert seems harsher, with overheating happening quickly even with no armour.

- Could it be possible to add a form of heat insulation to armour, like how some mods use honey, slime or ice?
- Alternatively, an armour type could be added, made of lightweight plant fibers or something like that, to protect against the heat.
- I noticed that resting under leaves is great to protect against overheating. I tested and noted that a roof of unlit campfires or trapdoors with/without carpets won't do the same. Is it possible or desirable to change it? It would allow many types of desert build designs to become fucntional.

This is all I have to note.
Keep up the amazing work!

**Comment by Globox1997** [comment]
I realized I forgot to delete a line which was the reason why the heat environment was more harsh than the cold, now the cold is harsh too^^ 
Added a new config called temperature_calculation_time which can set to a higher value like 40 to decrease the harshness.
Added a new item called Ice Pack which cools the player
Another armor isn't a bad idea but not in my scope currently
Not sure why the unlit campfires and trapdoors don't work honestly

**Comment by ramblinghaggis** [comment]
Could you add the ice pack to 1.18.1 version too please?

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest versions

**Comment by dull4h4n** [comment]
Wondered why I am overheating in the rain in the desert? It does not seem like normal factors that would mitigate heat or cold are considered in this mod, but that it rigidly requires the additional items or equipment.

**Comment by Globox1997** [comment]
Added a new cooling armor set plus you can enhance the armor with ice now to cool yourself down.
