### ISSUE TITLE
Faeture request | integration with the seasons mod

### ISSUE THREAD

**Issue by 32bitx64bit** [Globox1997/EnvironmentZ#36]
Would love to see integration with the 'Fabric seasons' would be lovely

Link to mod | https://www.curseforge.com/minecraft/mc-mods/fabric-seasons

**Comment by Globox1997** [comment]
Should be compatible out of the box :)
The biome temperature is the main integration here

**Comment by 32bitx64bit** [comment]
Alrighty!
