### ISSUE TITLE
Temperature indicator not appearing

### ISSUE THREAD

**Issue by StasGOP** [Globox1997/EnvironmentZ#38]
I love the added difficulty and integration but the mod doesn't appear on my bar i made sure the mod is on and that the cloth api is there too i deleted and downloaded the mod again but nothing
![Capture](https://user-images.githubusercontent.com/95861406/145400685-f4a1f381-97e1-4ea3-9002-5e06bc35aea9.PNG)

**Comment by Globox1997** [comment]
Might be fixed with [https://github.com/Globox1997/EnvironmentZ/commit/699a9331032ea83e677495ace1028696fb8274e5](https://github.com/Globox1997/EnvironmentZ/commit/699a9331032ea83e677495ace1028696fb8274e5)

**Comment by TobiPeterG** [comment]
> Might be fixed with [699a933](https://github.com/Globox1997/EnvironmentZ/commit/699a9331032ea83e677495ace1028696fb8274e5)

I have the same issue, I'm playing on 1.17.1, using a dedicated server running the world.
The temperature indicator never appears unfortunately

**Comment by Globox1997** [comment]
Out of time reasons I only develop further on the latest version so my only recommendation is to update the mod.
