### ISSUE TITLE
Temperature Indicator just a ragdoll(?) sprite

### ISSUE THREAD

**Issue by KielCoderTime** [Globox1997/EnvironmentZ#40]
Yeah its basically just what the title says. Here's a picture
![2021-12-15_16 33 46](https://user-images.githubusercontent.com/93207159/146152606-6f77309e-1860-4f23-b988-ccf4f093c893.png)
If it can help I'm playing with Better Minecraft fabric mods

**Comment by Globox1997** [comment]
So where is the issue? :D
