### ISSUE TITLE
Game crashes upon entering a world (1.18.1)

### ISSUE THREAD

**Issue by Givoric** [Globox1997/EnvironmentZ#41]
Crash log: https://pastebin.com/CX4FvwZP

**Comment by Globox1997** [comment]
It was an origins incompat, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/a1a6b6b0de1cbfb4ec87cba49b8a653a3ff0e91c](https://github.com/Globox1997/EnvironmentZ/commit/a1a6b6b0de1cbfb4ec87cba49b8a653a3ff0e91c)
