### ISSUE TITLE
Dying to the freezing effect doesn't show the correct death message

### ISSUE THREAD

**Issue by MarkNoName** [Globox1997/EnvironmentZ#42]
![2022-01-06_14 06 41](https://user-images.githubusercontent.com/35975662/148387695-31ddbc68-258d-466c-b9d4-b8d1a319ef6b.png)

**Comment by duckycaps** [comment]
I second this

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/364888ff1e57d4dd31ab88ebd797e7a3f0076459](https://github.com/Globox1997/EnvironmentZ/commit/364888ff1e57d4dd31ab88ebd797e7a3f0076459)
