### ISSUE TITLE
People are dying to freezing, but they have campfire and heating stones

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/EnvironmentZ#43]
In my Modpack the people ary dying to freezing altougth they having campfire and heating stones
I really would like to help you figuring this issue out, have also a server where you could test it.

https://www.curseforge.com/minecraft/modpacks/deathdusk [2.8.1]

**Comment by TheButterbrotMan** [comment]
Leather armor is protecting from freezing

**Comment by TheButterbrotMan** [comment]
Campfire and Heating Stones and Leather Armor protecting not, i am playing with Fabric Seasons (Spring, Summer), in a Taiga Biome. Maybe this helps.

**Comment by Globox1997** [comment]
Is this issue still existent?

**Comment by Globox1997** [comment]
Open again if still happening with the latest version
