### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BrokenDawn627** [Globox1997/EnvironmentZ#46]
when hold heated stone in offhand，it's durability decreases to 1%, then stop, and the first item in the inventory will change into the heated stone.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/EnvironmentZ/commit/0ef5fe111cbe9da3eed2098e19abad194b28e1d1](https://github.com/Globox1997/EnvironmentZ/commit/0ef5fe111cbe9da3eed2098e19abad194b28e1d1)
