### ISSUE TITLE
Thermostater

### ISSUE THREAD

**Issue by Laifsyn** [Globox1997/EnvironmentZ#47]
Insert a HUD-like data or Command for current temperature, or a literal thermostat. It's really hard to discern if I'm in a too cold environment, or am currently warm enough or viceversa

**Comment by Globox1997** [comment]
Working on it

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/EnvironmentZ/commit/81f1e58e9ef089e082865494e5a154191be6e07b](https://github.com/Globox1997/EnvironmentZ/commit/81f1e58e9ef089e082865494e5a154191be6e07b)
