### ISSUE TITLE
Overheating Doesn't Hurt

### ISSUE THREAD

**Issue by LeeroyGarfield** [Globox1997/EnvironmentZ#48]
Hello. It seems overheating doesn't hurt me at all. The indicator says it's already at maximum, but that's about it.

https://user-images.githubusercontent.com/87123836/154730810-145f7311-e899-42e0-b8c7-376d18baa014.mp4

Tested it on 1.18.1.

Here is the list of mods I've used:
- Cloth Config v6 6.2.57
- EnvironmentZ 1.2.1
- Fabric API 0.46.4+1.18

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/EnvironmentZ/commit/69b9996e46bda341023287f18238711a38bc465a](https://github.com/Globox1997/EnvironmentZ/commit/69b9996e46bda341023287f18238711a38bc465a)
Thanks for reporting :)
