### ISSUE TITLE
Icon mod problem 

### ISSUE THREAD

**Issue by majkkez** [Globox1997/EnvironmentZ#50]
Hello, I have a problem with the snow icon in the middle because I see a totem 
![Bez tytułu](https://user-images.githubusercontent.com/98131920/157371162-c0e556dc-5f0a-44e1-8e82-a1e69e1004cb.png)

**Comment by majkkez** [comment]
I know in the sceen Im on desert but its means nothing to the situation

**Comment by Globox1997** [comment]
The totem is there since the newer updates and will change to the old icons if the temperature is reached.
