### ISSUE TITLE
Nether Stops Temperature Change

### ISSUE THREAD

**Issue by pawbap** [Globox1997/EnvironmentZ#51]
When entering the Nether, the temperature you enter at stays while you're there. If I got to freezing, and it's chipping away at my health, then I enter a Nether portal, I stay frozen and keep hurting from the freeze even though I'm no longer in a cold area. ...At least, I doubt the Nether is very cold.

**Comment by Globox1997** [comment]
Fixed that with the latest version which I upload probably today
