### ISSUE TITLE
Temperature gauge

### ISSUE THREAD

**Issue by LordMeta** [Globox1997/EnvironmentZ#52]
This isn't an Issue but rather a suggestion. This mod makes the game Alot more Challenging and i love it :D but i really wish i had a way to read in game temperatures. please implement such an item :D

**Comment by Globox1997** [comment]
Pretty similar to #47
Do you think an item which then shows the env tmp and player tmp on the screen is a good solution or a config setting which always shows those informations?

**Comment by Globox1997** [comment]
Will close this due to [https://github.com/Globox1997/EnvironmentZ/issues/47](https://github.com/Globox1997/EnvironmentZ/issues/47)
