### ISSUE TITLE
Other mods supports?

### ISSUE THREAD

**Issue by LiangYin233** [Globox1997/EnvironmentZ#53]
Hi, are you considering support for compatible [farmers-delight-fabric](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric) and [culinaire](https://www.curseforge.com/minecraft/mc-mods/culinaire) mods? thx

**Comment by Globox1997** [comment]
Which features are you requesting, or what ideas do you have for compatibility? :)
