### ISSUE TITLE
Freezing death message text says "death.attack.freezing".

### ISSUE THREAD

**Issue by MScott7** [Globox1997/EnvironmentZ#54]
When I freeze to death the death message in chat says "death.attack.freezing", which doesn't look intentional. 

Among the other mods I'm using are Hardcore Revival and Death Knell, the only two that I can think of that might interact with this death message. 

Using Minecraft 1.18.2, Fabric 0.14.7, Fabric API 0.56.0+1.18.2, EnvironmentZ 1.2.2.
My latest.log in case it helps somehow: https://pastebin.com/8TgcA5LW

**Comment by MScott7** [comment]
Upon reading through the closed issues it looks like this is the same problem as #42

**Comment by Globox1997** [comment]
Definitely fixed with a later version and can be fixed via a resource pack
