### ISSUE TITLE
[Issue] Cold temperature doesn't go down

### ISSUE THREAD

**Issue by Zensuyo** [Globox1997/EnvironmentZ#55]
I'm wearing a full armor with fur and carrying heated stone and near to a bonfire or campfire doesn't change the status temperature to warm. Im using environmentz 1.2.2 / 1.18.2

**Comment by Aiva418** [comment]
I second this, and it's a major problem. I stood in lava to set myself on fire and, after a full minute of being next to it and keeping myself from burning alive, I'm still freezing to death.
I'm using the same version.

**Comment by Globox1997** [comment]
mh that is an issue but for an older version...

**Comment by Globox1997** [comment]
With a later version you can now set each temperature affection of blocks with a datapack.
