### ISSUE TITLE
Add support for map makers.

### ISSUE THREAD

**Issue by JitterySkywalker567** [Globox1997/EnvironmentZ#56]
Perhaps you could add a command that increases or decreases temperature in a specified area, alternatively you could have blocks you put in corners of rooms that have the same effect.

**Comment by Globox1997** [comment]
Added a couple of blocks which increase the temperature with [https://github.com/Globox1997/EnvironmentZ/commit/07a6d8bc5659b09606e69dc0c81a6d34fc3194fd](https://github.com/Globox1997/EnvironmentZ/commit/07a6d8bc5659b09606e69dc0c81a6d34fc3194fd)
EnvironmentZ uses the biome temperature which is hardcoded I think
