### ISSUE TITLE
Add config to help modify which armor prevents cold

### ISSUE THREAD

**Issue by TheRobberPanda** [Globox1997/EnvironmentZ#58]
As in the tittle. I dont want iron armor to help against cold weather, if anything it should make the player colder, that's why I think its a good idea to be able to type in which kinds of armor help against weather, even better if you can decide wether its cold or warm protective armor.

**Comment by Globox1997** [comment]
There are two item tags, one for the cold environments and one for the hot environments.
warm_armor as the name says and allowed_armor which allows the armor to be worn in hot environments without affecting the player
