### ISSUE TITLE
Magma Blocks as a warming block

### ISSUE THREAD

**Issue by Valtyrian** [Globox1997/EnvironmentZ#59]
can you tell me how I can add Magma Blocks as a warming block? all I've ever seen is 'put in as a tag' but there seems to be no actually step by step on how to do this. or could you add this in an update? it's frustrating only being able to use campfires.

**Comment by Valtyrian** [comment]
also have you thought of setting the default settings to something more optimal.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/EnvironmentZ/commit/07a6d8bc5659b09606e69dc0c81a6d34fc3194fd](https://github.com/Globox1997/EnvironmentZ/commit/07a6d8bc5659b09606e69dc0c81a6d34fc3194fd) while standing on it
