### ISSUE TITLE
[1.3.1] Incompatibility with Origins 1.7.0 (Minecraft 1.19.2)

### ISSUE THREAD

**Issue by Lilwhiteshark** [Globox1997/EnvironmentZ#61]
**Minecraft 1.19.2
EnvironmentZ 1.3.1
Origins 1.7.0**

Attempting to click the "Single Player" button from the title screen crashes the game, crashlog attached below (the OriginCommandMixin compat from EnvrionmentZ seems to be causing an issue).

[crashlog](https://gist.github.com/Lilwhiteshark/362615ecc00b76f2304a04d5445f08df)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/c6503c1518af05c6517554ba2efa6750fe15cfdf](https://github.com/Globox1997/EnvironmentZ/commit/c6503c1518af05c6517554ba2efa6750fe15cfdf)
