### ISSUE TITLE
Crashing after Feezing

### ISSUE THREAD

**Issue by SHXRKIEgg** [Globox1997/EnvironmentZ#62]
After Freezing there is a crash and then I am unabke to join the world back, Removing the mod I am abke to join back my world.
[crash-2022-09-08_06.15.14-client.txt](https://github.com/Globox1997/EnvironmentZ/files/9521976/crash-2022-09-08_06.15.14-client.txt)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/EnvironmentZ/commit/af88880c400401da9c8a83b76b6f19860adbf7c6](https://github.com/Globox1997/EnvironmentZ/commit/af88880c400401da9c8a83b76b6f19860adbf7c6)
