### ISSUE TITLE
freezing to death doesnt show up correctly

### ISSUE THREAD

**Issue by Vinson8970** [Globox1997/EnvironmentZ#64]
![2022-09-16_23 52 11](https://user-images.githubusercontent.com/108201128/190841064-1d8bab7c-0f8d-468c-a8f2-89f253d93a3b.png)
[mod list.txt](https://github.com/Globox1997/EnvironmentZ/files/9591019/mod.list.txt)

**Comment by Vinson8970** [comment]
its also on Fabric 1.18.2

**Comment by Globox1997** [comment]
Same as [https://github.com/Globox1997/EnvironmentZ/issues/54](https://github.com/Globox1997/EnvironmentZ/issues/54)
