### ISSUE TITLE
Incompatible with Origins

### ISSUE THREAD

**Issue by SHXRKIEgg** [Globox1997/EnvironmentZ#65]
EnviromentZ & Dehydration is Incompatible with Latest Origins Version

EnviromentZ: [crash-2022-09-21_18.21.55-client.txt](https://github.com/Globox1997/EnvironmentZ/files/9615677/crash-2022-09-21_18.21.55-client.txt)
Dehydration: [crash-2022-09-21_18.19.37-client.txt](https://github.com/Globox1997/EnvironmentZ/files/9615685/crash-2022-09-21_18.19.37-client.txt)

**Comment by Globox1997** [comment]
Thanks for report, fixed both, this with [https://github.com/Globox1997/EnvironmentZ/commit/abad9533c15cefe74879a57bc9689d1c29f2b577](https://github.com/Globox1997/EnvironmentZ/commit/abad9533c15cefe74879a57bc9689d1c29f2b577)
