### ISSUE TITLE
Incompatible with Optifine?

### ISSUE THREAD

**Issue by DA-WNTR-NX** [Globox1997/EnvironmentZ#66]
Sorry if this issue has already been addressed, I didn't find any answers. 

It seems that EnvironmentZ crashes the game on startup when paired with Optifine (and Optifabric), I tested the Dehydration mod with EnvironmentZ and Optifine each individually, both combinations worked well but could not function when combined.

I'm not sure if there is an issue with the mod, or if it's a problem on my end.

**Comment by Globox1997** [comment]
Can you send the crash log pls?

**Comment by DA-WNTR-NX** [comment]
Apologies, took some time to google how it works, I couldn't locate a crash report or JVM report, don't know if this helps.
[latest.log](https://github.com/Globox1997/EnvironmentZ/files/9752185/latest.log)

Sorry if I'm lacking knowledge and logic on this subject.

**Comment by Globox1997** [comment]
latest.log is exactly what I need when no crash log was generated :)
it looks like optifine is indeed incompatible with environmentz but from optifines side.
I recommend to switch to Iris mod and all performance mods you can get

**Comment by DA-WNTR-NX** [comment]
Optifine...sigh...

Thank you for your help and patience!
