### ISSUE TITLE
Repairing enchanted Ice Pack removes enchantments

### ISSUE THREAD

**Issue by bmezhibovskiy** [Globox1997/EnvironmentZ#67]
An Ice Pack can be enchanted with Mending and Unbreaking. However, repairing it with ice removes all enchantments.

**Comment by Globox1997** [comment]
Removed enchantability with [https://github.com/Globox1997/EnvironmentZ/commit/38b48fb4d849fc0d0a559cb8330d0b1e6ab4e30b](https://github.com/Globox1997/EnvironmentZ/commit/38b48fb4d849fc0d0a559cb8330d0b1e6ab4e30b)
