### ISSUE TITLE
no temperature change 

### ISSUE THREAD

**Issue by nico6789** [Globox1997/EnvironmentZ#69]
hi,
i've installed the mod not so long ago and i've realise that whereas  im in a desert or lost in a cold forest, my temperature dont change at all. I can stay 10 min in a blizzar with nothing on my shoulder and i don't get cold.
One reson could be incompatibility but I havn't fond anything on it yet, I have a bunch of mods  wich modify the world generation so that could be the cause? 
don't know if anyone can help me

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by Globox1997** [comment]
Reopen if still happening on the latest version.
