### ISSUE TITLE
Campfires not working to warm up cold players

### ISSUE THREAD

**Issue by honeyleis** [Globox1997/EnvironmentZ#70]
I use EnvironmentZ in Medieval Minecraft and play as the pixie origin, meaning I can't wear chestplates to stay warm, and have to rely on heat sources to keep myself from freezing. I have a bunch of campfires set around my base for winter, but as the next winter cycle came up, the campfires weren't working at all. They worked for one winter cycle, but the next one, I continuously froze to death despite standing literally a block away from the campfire- before the freezing snowflake icon appeared on screen. I ended up just having to force skip winter because nothing worked to keep me warm.

Campfires and other heat sources suddenly stopped working and it seems like they aren't working for other players either.

update: i've also tried giving the warming status for several minutes and even being cold doesn't go away. a friend also literally cannot stop overheating despite being in a non-extreme biome- the thermometer isn't frozen or on fire. i think freezing and heating might be broken in general?

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by mantis2600** [comment]
This is still an issue for my pixie player on 1.3.3.

**Comment by mantis2600** [comment]
Confirm that my dwarf player is also not warmed by fires.

**Comment by mantis2600** [comment]
We're playing Medieval MC Fabric, it seems like part of the issue involves the interplay with the Fabric Seasons mod's winter.

**Comment by mantis2600** [comment]
After some extensive testing, I think it is working as intended, it looks like the amount the items heat you is too low for my players tastes. I think we can fix it to our liking in the configs. Thanks!

**Comment by are** [comment]
@mantis2600 have you figured out what config settings you needed to change? I'm also playing on Medieval MC Pixie and I have no idea how to approach this

**Comment by Globox1997** [comment]
Reopen if persistent on the latest version.
