### ISSUE TITLE
Potion of overheating - This should slow overheating

### ISSUE THREAD

**Issue by APinchofDill** [Globox1997/EnvironmentZ#72]
The "potion of overheating" should be compatible with this mod to allow for more time to be spent in places like the nether. Maybe just not blur vision / take damage while the potion is active for example.

**Comment by Globox1997** [comment]
Tweaked the effects of the potions with [https://github.com/Globox1997/EnvironmentZ/commit/40433e88dc12dc7bebae6c2d7e17b6a0a957461e](https://github.com/Globox1997/EnvironmentZ/commit/40433e88dc12dc7bebae6c2d7e17b6a0a957461e)
Now they increase/decrease the player temperature too
