### ISSUE TITLE
surviving in the nether/deleting mod

### ISSUE THREAD

**Issue by YoungerMarrow** [Globox1997/EnvironmentZ#73]
how do you survive longer in the nether? it seems i overheat so quickly that i can't even begin to do anything. If no solution, is there a way to completely turn off the mod without having to delete it, because when i delete the mod it alters my whole world and i'm not able to access it.

**Comment by Globox1997** [comment]
Can you send the latest log when it alters the whole world?

**Comment by Globox1997** [comment]
Reopen when persistent on the latest version.
