### ISSUE TITLE
Origins (Fabric) compatibility

### ISSUE THREAD

**Issue by Astraios117** [Globox1997/EnvironmentZ#75]
I'd like to suggest some compatibility features with Origins (Fabric). Origins has some character choices based around temperature, like the yeti for cold environments or the blazeborn for hot environments. It would be awesome if these choices also had an impact with EnvironmentZ. As of now if both mods are present counter intuitive things happen, such as the yeti freezing to death in snow biomes. I think characters should be immune to their preferred weather and extra susceptible to the other. I believe this would create a more enjoyable experience in modpacks that have both of these great mods. I have also made this suggestion on the Origins page

**Comment by Globox1997** [comment]
Origins provide a command callback which can be used to remove affection of hot and or cold environments

**Comment by Astraios117** [comment]
I see, I hadn't realized it was very customizable. I do have a couple of questions though, say I wanted to use an EnvironmentZ command to make an origin immune to cold, would the command be "/environment affection playername cold 0"? Do I need to include playername or can that part be left out. What are the ranges for the bool value? Also in the resistance command what is the default resistance value, is it 0? Thanks!

**Comment by Globox1997** [comment]
Please check out my discord for questions :)
