### ISSUE TITLE
Disappearing head with the Wolf Pelt armour

### ISSUE THREAD

**Issue by Proxima-Ch2426** [Globox1997/EnvironmentZ#76]
![2022-12-09_18 04 09](https://user-images.githubusercontent.com/120201446/206754124-7d1ff44f-869d-4aec-bb6e-123a29a75dbe.png)
![2022-12-09_18 03 22](https://user-images.githubusercontent.com/120201446/206754132-3609ff7d-bcb7-4a4a-a5fc-350b2ffc452b.png)
![2022-12-09_18 08 02](https://user-images.githubusercontent.com/120201446/206754451-46424cc7-eb68-4314-9053-9169b37f533c.png)

Without wearing the wolf pelt helmet, the player head is still visible. However when putting it on, the wolf head blocks the player's view and upon reloading the resource packs (F3+T) the whole helmet and player head disappears? Are there any mod conflicts that could cause this?

**Comment by Globox1997** [comment]
Tried to reproduce this bug but seems like it is a mod incompat.
To figure out which mod causes this, I recommend to use the 50/50 method for disabling mods at a time.

**Comment by Globox1997** [comment]
Reopen if persistent on the latest version + the info which mod makes it incompatible.
