### ISSUE TITLE
fix enviromentz

### ISSUE THREAD

**Issue by RGAZN** [Globox1997/EnvironmentZ#79]
Ice packs need to work so people can spend more than 5 minutes in the nether. More things need to be made to make weather more tolerable. weather is way to harsh and no way to deal with it. fabric medieval mc v14.5 1.19.2 campfire don't work and heating stones also need a buff and need to last longer takes up too many spaces in my inventory when I want to go outside to explore during winter season. NEED MORE ARMORS FOR PROTECTION AGAINST ENVIROMENTZ MOD!

**Comment by Globox1997** [comment]
This can be done via datapacks. Armor can get added to the tag and can have an affect on the player when set in datapack. Check out the readme for more info.
