### ISSUE TITLE
Campfires don't heat you up

### ISSUE THREAD

**Issue by moshner** [Globox1997/EnvironmentZ#80]
EnvironmentZ Version 1.3.4
Modpack: Medieval Minecraft MC [FABRIC} - MMC1

I'm literally standing on a campfire and it is not warming me up.

Config:
{
	// Increase for less harsh environments
	"temperature_calculation_time": 200,
	"icon_x": 7,
	"icon_y": 52,
	"thermometer_icon_x": 140,
	"thermometer_icon_y": 32,
	"show_thermometer": true,
	// Below this biome temp - start undercooling
	"biome_cold_temp": 0.4000000059604645,
	// Below this biome temp - start freezing
	"biome_freeze_temp": 0.20000000298023224,
	"allow_all_armor": true,
	// Caution! This could decrease performance
	"heating_up_block_range": 3,
	// Protection amount is reduced every second
	"max_cold_protection_amount": 120,
	// Protection amount is added every second
	"cold_protection_amount_addition": 20,
	// White overlay while in cold biomes
	"cold_overlay": true,
	"shaking_screen_effect": true,
	// Above this biome temp - start overheating
	"biome_hot_temp": 1.2000000476837158,
	// Above this biome temp - start overheating
	"biome_overheat_temp": 1.600000023841858,
	// Handles thirst when Dehydration mod is loaded
	"overheating_exhaustion": 0.5,
	// Protection amount is reduced every second
	"max_heat_protection_amount": 120,
	// Protection amount is added every second
	"heat_protection_amount_addition": 20,
	// Undo dehydration mod compat
	"exhaustion_instead_dehydration": false,
	"blur_screen_effect": true
}
![2023-01-04_13 59 59](https://user-images.githubusercontent.com/3300206/210640587-fc8c2511-0751-40fb-8ab0-8d855b735594.png)

**Comment by Proxima-Ch2426** [comment]
Yep this is a big problem right now. The only way I could keep myself warm was by constantly using the furnace. In the latest update it was supposed to increase the strength of campfires, but I'm still freezing to death with even two campfires! You could also use heated stones, but you'll need a stone grinder to obtain them. These are the solutions for the time being... hopefully it could be fixed in the next update 🙃

**Comment by RCertainty** [comment]
I encounter this exact same issue, it seems it broke with the "reworked temperature system" update 2.0.0 of EnviromentalZ

**Comment by Globox1997** [comment]
This got fixed with the 2.0.0 update
