### ISSUE TITLE
Add options for the Thermometer

### ISSUE THREAD

**Issue by jmadarg** [Globox1997/EnvironmentZ#84]
Some modded gameplays may have a considerable amount of HUD elements, making the placement of the vertical thermometer a bit hard to manage.
I propose as solution adding an horizontal option (that could be placed in a similar way to the xp bar or hp bar) or a circular option that could go around the freezing/overheating indicator.
Also, another thing that could help would be an having a button to be able to drag and drop the icon where you want to (like [InventoryHUD+](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)  does)

**Comment by FormBurden** [comment]
While not a UI element, there is a config option to edit the X and Y axis. Check the mods config to change it.

**Comment by jmadarg** [comment]
I know about that feature, but even then sometimes is hard to find a good place for it.

**Comment by FormBurden** [comment]
Yeah, I know the feeling. It took me 45 min of playing with the x and y just to find the spot I wanted it.

**Comment by Globox1997** [comment]
Even tho this is not a bad suggestion, I have no plans to add such thermometer option.
