### ISSUE TITLE
[1.19.2] Dreadful execution; mod unplayable in certain biomes

### ISSUE THREAD

**Issue by definitelynotklip** [Globox1997/EnvironmentZ#89]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

This mod arbitrarily enables extreme weather conditions in specific biomes with absolutely _no_ feasible way to address them from the player's perspective. For example, if you happen to spawn into _any_ snowy biome, you are quite literally **dead** within three to four real-life minutes as you are expected to:
1. Make an axe and a pickaxe,
2. Mine enough stone and coal (or wood),
3. Make a furnace,
4. Make a stonecutter,
5. Wait for a bunch of rocks to heat up.
OR
6. Obtain a full set of leather / wolf armor.

Alternatively, you're expected to fight off a bunch of polar bears, make a smithing table, then upgrade armor that isn't those two sets with insulation, all within _minutes_ of spawning into a world. Campfires do absolutely jack to address the cold, as does going indoors (I tried). Standing next to a lava source only heats you up if you are _directly adjacent_ to it - take a couple of steps in any direction and you're back to freezing within seconds. You can't move away to collect resources or even find a better biome, you just outright die.

The same can be said about heat; if you spawn into a savannah you have a few minutes to get the hell out of there or you start burning up - you can't dive into water to cool off, you can't cool off in the rain, you can't stand in the shade, you lose more Dehydration thirst than you can feasibly purify with 3 bottles of water alone, and on top of that you can't see shit.

These issues are then exacerbated by mods like No Tree Punching, which slow the earlygame down, or world generators like Terra, Terralith, Tectonic, that generally spawn larger biomes, have more biomes with extreme weather in the mix, and provide uneven terrain that is harder to traverse.

This mod should:
1. **By DEFAULT** (WITHOUT forcing players to reconfigure it) extend the time it takes to die of heat or chill, OR:
2. **By DEFAULT** ensure players cannot spawn into a biome with extreme weather in it.
3. Better communicate that the biome the player is in, or is about to enter, will have serious consequences on their health.
4. Provide a set of clothes that can be found or crafted, slowing down heating/freezing with common materials (i.e. wool).
5. Use the environment as an equalizer better - standing near a campfire or lava, standing in the shade, swimming in water, being underground or indoors, should all affect freezing or heating better.
6. Properly consider level of activity - strafing, digging, mining or placing blocks, engaging in combat, should all slow down freezing.

**Comment by Globox1997** [comment]
This is great feedback, do you have discord?

**Comment by xR4YM0ND** [comment]
I made a test datapack where i changed almost all values.
The height, body_wetness & body_protection is not changed properly.

Could you test this and tell us your opinion on the changes
[environmentz test datapack.zip](https://github.com/Globox1997/EnvironmentZ/files/11360964/environmentz.test.datapack.zip)

**Comment by Globox1997** [comment]
With a later update, a lot got changed, might be playable now.
