### ISSUE TITLE
EnvironmentZ Armor

### ISSUE THREAD

**Issue by finlader** [Globox1997/EnvironmentZ#99]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

21 HF

### Describe the Issue

When playing on the server that our friends have, we noticed that the armor meant to combat the weather/temperatures wasn't working, and even making the ice pack or heating stones didn't work while they were in our inventory. It only worked if they were in our hand or offhand. We ended up deleting EnvironmentZ from the server and our own modpacks.

### latest.log

[latest.log](https://github.com/Globox1997/EnvironmentZ/files/11900844/latest.log)

### Do you use any other mods except the required ones?

The mod is paired with Medieval Minecraft FABRIC by SHXRKIE. Those are the mods we all use.

**Comment by Globox1997** [comment]
Reopen if persistent on the latest version.
